#ifndef NEURALNETWORK_GLOBAL_H
#define NEURALNETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEURALNETWORK_LIBRARY)
#  define NEURALNETWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEURALNETWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEURALNETWORK_GLOBAL_H
